spring.application.name=Project
# Database Connection Settings
spring.datasource.url=jdbc:postgresql://ep-super-waterfall-adwwmjku-pooler.c-2.us-east-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_2I6MNrPxWcGt
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Connection Pooling (Recommended for Neon)
spring.datasource.hikari.maximum-pool-size=10

# SpringBoot Initialization Settings
# Tell Spring to run data.sql after Hibernate creates tables
# spring.jpa.defer-datasource-initialization=true
# spring.sql.init.mode=always
# # Disable Spring's default schema initialization for running application and tests

# # Use the 'data-locations' property instead of 'schema-locations'
# spring.sql.init.data-locations=classpath:data.sql